var = input("Digite algo:")
print(type(var))
print("Só tem espaços?", var.isspace())
print("É númerico?".format(var.isnumeric()))
print("É alfabético?".format(var.isalpha()))
print("É alfanumerico?", var.isalnum())
print("Está em maiúscula?", var.isupper())
print("Está em minúscula?", var.islower())
print("Está capitalizada?", var.istitle())
